name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Check out the repo
    - uses: actions/checkout@v2

    # Setup JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    # Build the jar
    - name: Build with Maven
      run: mvn -B -DskipTests clean package assembly:single --file pom.xml

    # Create github release
    - name: Create Github release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
            target/dhinabot*dependencies.jar